name: Fare Calculator CI/CD

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "**.md"
      - "doc/**"
      - "Fare-Calculator-capture-version-pc/**"
      - ".gitignore"

  workflow_dispatch:

jobs:
  pipeline:
    uses: projet-synthese-gi26/workflows/.github/workflows/react-vite-ci-cd.yml@main
    with:
      app_name: fare-calculator-web
      node_version: "20"
      run_lint: true
    secrets:
      PERSONAL_ACCESS_TOKEN:             ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      REGISTRY_NAMESPACE:                ${{ secrets.REGISTRY_NAMESPACE }}
      SSH_PRIVATE_KEY:                   ${{ secrets.SSH_PRIVATE_KEY }}
      REMOTE_USER:                       ${{ secrets.REMOTE_USER }}
      REMOTE_HOST:                       ${{ secrets.REMOTE_HOST }}
      DEPLOY_DELAY:                      ${{ secrets.DEPLOY_DELAY }}
      VITE_API_BASE_URL:                 https://traefikdev.yowyob.com/fare-calculator
      VITE_API_KEY:                      974e9428-6ce2-48e7-b74b-93f572007ef8
      VITE_MAPBOX_TOKEN:                 pk.eyJ1IjoibTJnaSIsImEiOiJjbWhramlqcnIwYW5rMmlzY3ViZmg1NGFmIn0.q3XQxQTte7ADbn32fwFh-g
      VITE_MAPBOX_STYLE:                 mapbox://styles/mapbox/streets-v12
      VITE_NOMINATIM_BASE_URL:           https://nominatim.openstreetmap.org
      VITE_OPENMETEO_BASE_URL:           https://api.open-meteo.com/v1
      VITE_MODE:                         development
      VITE_ENABLE_GEOLOCATION:           true
      VITE_CACHE_TTL:                    3600000
      VITE_API_TIMEOUT:                  30000
      VITE_GA_ID:                        "xxxxxxx"
      VITE_FIREBASE_API_KEY:             AIzaSyAvveEEwmsXRXHGslRlYrPby-oFJwGMd8E
      VITE_FIREBASE_AUTH_DOMAIN:         farecal-ae3f3.firebaseapp.com
      VITE_FIREBASE_PROJECT_ID:          farecal-ae3f3
      VITE_FIREBASE_STORAGE_BUCKET:      farecal-ae3f3.firebasestorage.app
      VITE_FIREBASE_MESSAGING_SENDER_ID: 21858050203
      VITE_FIREBASE_APP_ID:              1:21858050203:web:ad1db863dd6cc88793a63e
      VITE_FIREBASE_BILLING_ENABLED:     false